var spritesheetTilesDefault={tiles:[{fromX:0,fromY:0,width:100,height:100,top:0,right:0,bottom:1,left:1,hitboxes:[{fromX:0,fromY:45,toX:55,toY:55},{fromX:45,fromY:45,toX:55,toY:100}]},{fromX:100,fromY:0,width:100,height:100,top:0,right:1,bottom:0,left:1,hitboxes:[{fromX:0,fromY:45,toX:100,toY:55}]},{fromX:200,fromY:0,width:100,height:100,top:0,right:1,bottom:1,left:0,hitboxes:[{fromX:45,fromY:45,toX:100,toY:55},{fromX:45,fromY:45,toX:55,toY:100}]},{fromX:300,fromY:0,width:100,height:100,top:0,right:1,
bottom:1,left:1,hitboxes:[{fromX:0,fromY:45,toX:100,toY:55},{fromX:45,fromY:45,toX:55,toY:100}]},{fromX:400,fromY:0,width:100,height:100,top:1,right:0,bottom:0,left:1,hitboxes:[{fromX:45,fromY:0,toX:55,toY:55},{fromX:0,fromY:45,toX:55,toY:55}]},{fromX:500,fromY:0,width:100,height:100,top:1,right:0,bottom:1,left:0,hitboxes:[{fromX:45,fromY:0,toX:55,toY:100}]},{fromX:600,fromY:0,width:100,height:100,top:1,right:0,bottom:1,left:1,hitboxes:[{fromX:45,fromY:0,toX:55,toY:100},{fromX:0,fromY:45,toX:55,toY:55}]},
{fromX:700,fromY:0,width:100,height:100,top:1,right:1,bottom:0,left:0,hitboxes:[{fromX:45,fromY:0,toX:55,toY:55},{fromX:45,fromY:45,toX:100,toY:55}]},{fromX:800,fromY:0,width:100,height:100,top:1,right:1,bottom:0,left:1,hitboxes:[{fromX:0,fromY:45,toX:100,toY:55},{fromX:45,fromY:0,toX:55,toY:55}]},{fromX:900,fromY:0,width:100,height:100,top:1,right:1,bottom:1,left:0,hitboxes:[{fromX:45,fromY:0,toX:55,toY:100},{fromX:45,fromY:45,toX:100,toY:55}]},{fromX:1E3,fromY:0,width:100,height:100,top:1,right:1,
bottom:1,left:1,hitboxes:[{fromX:0,fromY:45,toX:100,toY:55},{fromX:45,fromY:0,toX:55,toY:100}]}]},spritesheetVehicleDefault={vehicle:[{fromX:0,fromY:0,width:25,height:25,hitboxes:[]}]},RR={el:{},ctx:{},state:{isRunning:!1,level:1},parseDOM:function(){RR.el.countdown=document.getElementById("CountDown");RR.el.messageBox=document.getElementById("MessageBox");RR.el.btnStartGame=document.getElementById("BtnStartTheGame");RR.el.canvasFloor=document.getElementById("Map-Floor");RR.el.canvasPlayer=document.getElementById("Map-Player");
RR.ctx.floor=RR.el.canvasFloor.getContext("2d");RR.ctx.player=RR.el.canvasPlayer.getContext("2d");RR.el.uiLevel=document.getElementById("PlayerLevelValue");RR.el.uiLives=document.getElementById("PlayerLivesValue")},resizeCanvases:function(){var a=100*RR.config.map.cols,c=100*RR.config.map.rows;RR.el.canvasFloor.setAttribute("width",a);RR.el.canvasFloor.setAttribute("height",c);RR.el.canvasPlayer.setAttribute("width",a);RR.el.canvasPlayer.setAttribute("height",c)},getRandomInt:function(a,c){var b=
Math.ceil(a);return Math.floor(Math.random()*(Math.floor(c)-b+1))+b},inRange:function(a,c,b){return a>=c&&a<=b},rectanglesIntersect:function(a,c){return!(c.fromX>a.toX||c.fromY>a.toY||c.toY<a.fromY||c.toX<a.fromX)},setup:function(){RR.resizeCanvases();RR.Map.init(RR.el.canvasFloor,RR.ctx.floor,RR.Sprites.stack.tiles,RR.config.map.rows,RR.config.map.cols);RR.Player.init(RR.el.canvasPlayer,RR.ctx.player,RR.Sprites.stack.vehicle);RR.Map.generateNewMap();RR.Player.drawSprite();RR.Game.init();RR.Controls.init();
RR.Countdown.init(RR.el.countdown,RR.el.canvasFloor.width,RR.el.canvasFloor.height,RR.Player.startEngine);RR.el.btnStartGame.addEventListener("click",RR.handleBtnStartGame)},handleBtnStartGame:function(a){a.preventDefault();RR.el.messageBox.classList.add("hide");RR.Countdown.start()},init:function(a){if("object"!==typeof a)return console.log("Critical Error: Missing Game Configuration!"),!1;RR.config=a;"boolean"===typeof RR.config.isDevMode&&(RR.isDevMode=RR.config.isDevMode);RR.parseDOM();RR.Sprites.load(RR.config.sprites,
RR.setup)},Controls:{}};
RR.Controls.handleKeyDown=function(a){a.preventDefault();switch(a.keyCode){case 68:0===RR.Player.state.angle?RR.Player.rotateClockwise():180===RR.Player.state.angle&&RR.Player.rotateAntiClockwise();break;case 65:180===RR.Player.state.angle?RR.Player.rotateClockwise():RR.Player.rotateAntiClockwise();break;case 83:90===RR.Player.state.angle?RR.Player.rotateClockwise():270===RR.Player.state.angle&&RR.Player.rotateAntiClockwise();break;case 87:90===RR.Player.state.angle?RR.Player.rotateAntiClockwise():270===
RR.Player.state.angle&&RR.Player.rotateClockwise()}};RR.Controls.init=function(){window.addEventListener("keydown",RR.Controls.handleKeyDown,!1)};RR.Countdown={element:{},canvasWidth:0,canvasHeight:0,callback:{},interval:{},value:0};RR.Countdown.centerElement=function(){RR.Countdown.element.style.left=RR.Countdown.canvasWidth/2-RR.Countdown.element.offsetWidth/2+"px";RR.Countdown.element.style.top=RR.Countdown.canvasHeight/2-RR.Countdown.element.offsetHeight/2+"px"};RR.Countdown.hide=function(){RR.Countdown.element.classList.add("hide")};
RR.Countdown.show=function(){RR.Countdown.element.innerText=RR.Countdown.value;RR.Countdown.element.classList.remove("hide");RR.Countdown.centerElement()};RR.Countdown.start=function(){RR.Countdown.reset();RR.Countdown.show();RR.Countdown.interval=setInterval(RR.Countdown.run,1E3)};RR.Countdown.run=function(){--RR.Countdown.value;0>RR.Countdown.value?RR.Countdown.stop(!0):RR.Countdown.element.innerText=RR.Countdown.value};
RR.Countdown.stop=function(a){a="boolean"===typeof a?a:!1;clearInterval(RR.Countdown.interval);RR.Countdown.hide();a&&"function"===typeof RR.Countdown.callback&&RR.Countdown.callback()};RR.Countdown.reset=function(){RR.Countdown.value=5};RR.Countdown.init=function(a,c,b,d){RR.Countdown.element=a;RR.Countdown.canvasWidth=c;RR.Countdown.canvasHeight=b;RR.Countdown.callback=d;RR.Countdown.centerElement()};RR.Game={directional:{}};
RR.Game.playNextLevel=function(){RR.state.level+=1;RR.Player.state.lives=6;RR.Game.play()};RR.Game.replayLevel=function(){--RR.Player.state.lives;0>RR.Player.state.lives?alert("G A M E    O V E R"):RR.Game.play()};RR.Game.play=function(){RR.Map.ctx.clearRect(0,0,RR.Map.canvas.width,RR.Map.canvas.height);RR.Map.generateNewMap();RR.Player.reset(RR.Player.state.lives);RR.Player.clearAll();RR.Player.drawSprite();RR.Game.updateUi();RR.Countdown.start()};
RR.Game.updateUi=function(){RR.el.uiLevel.innerText=RR.state.level;RR.el.uiLives.innerText=RR.Player.state.lives};
RR.Game.loop=function(){if(!1!==RR.state.isRunning){var a=new RR.Vector2(RR.Player.state.pos.x+RR.Game.directional[RR.Player.state.angle].x*RR.Player.state.speed,RR.Player.state.pos.y+RR.Game.directional[RR.Player.state.angle].y*RR.Player.state.speed);RR.Player.clearSprite();RR.Player.state.pos.x=a.x;RR.Player.state.pos.y=a.y;RR.Player.state.tile.row=Math.floor(RR.Player.state.pos.y/100);RR.Player.state.tile.col=Math.floor(RR.Player.state.pos.x/100);RR.Map.checkCollision(a,RR.Player.state.angle,RR.Player.state.tile.row,
RR.Player.state.tile.col)?(RR.Player.stopEngine(),alert("BOOM! You've hit a wall!"),RR.Game.replayLevel()):RR.Player.state.pos.x>RR.Map.canvas.width?(RR.Player.stopEngine(),alert("CONGRATULATIONS!\nYou have mastered this level!"),RR.Game.playNextLevel()):(RR.Player.drawSprite(),window.requestAnimationFrame(RR.Game.loop))}};RR.Game.getNextGridTile=function(a,c,b){a+=RR.Game.directional[b].y;c+=RR.Game.directional[b].x;return 0>a||0>c||a>=RR.config.map.rows||c>=RR.config.map.cols?!1:{row:a,col:c}};
RR.Game.init=function(){RR.Game.directional={0:new RR.Vector2(0,-1),90:new RR.Vector2(1,0),180:new RR.Vector2(0,1),270:new RR.Vector2(-1,0)}};RR.Map={canvas:{},ctx:{},sprite:{},floorColor:"#4eba04",wallColor:"#404040",borderWidth:20,tileIndexPool:[],dimTiles:0,tileMap:[],borderCollisionMap:[],collisionMap:[],maxRows:0,maxCols:0};RR.Map.drawEmptyTile=function(a,c){RR.Map.ctx.fillStyle=RR.Map.floorColor;RR.Map.ctx.fillRect(100*a,100*c,100,100)};
RR.Map.drawOuterBorder=function(){RR.Map.ctx.strokeStyle=RR.Map.wallColor;RR.Map.ctx.lineWidth=RR.Map.borderWidth;RR.Map.ctx.strokeRect(0,0,RR.Map.canvas.width,RR.Map.canvas.height)};RR.Map.drawFinish=function(){var a=100*(RR.config.map.cols-1),c=100*(RR.config.map.rows-1),b=100-RR.Map.borderWidth/2,d=100-RR.Map.borderWidth/2;RR.Map.ctx.fillStyle=RR.Map.floorColor;RR.Map.ctx.fillRect(a,c,b,d);RR.Map.ctx.fillRect(a+b,c,RR.Map.borderWidth/2,60)};
RR.Map.drawStart=function(){RR.Map.ctx.fillStyle=RR.Map.floorColor;RR.Map.ctx.fillRect(0,0,100,100)};RR.Map.generatTilePool=function(){var a=RR.config.map.rows*RR.config.map.cols,c=RR.Map.sprite.data.length,b;RR.Map.tileIndexPool=[];for(b=0;b<a;b+=1)RR.Map.tileIndexPool.push(RR.getRandomInt(0,c-1))};RR.Map.drawTile=function(a,c,b){RR.Map.ctx.drawImage(RR.Map.sprite.img,b.fromX,b.fromY,b.width,b.height,100*c,100*a,100,100)};
RR.Map.drawMap=function(){var a,c;for(c=0;c<RR.Map.maxRows;c+=1)for(a=0;a<RR.Map.maxCols;a+=1)RR.Map.drawTile(c,a,RR.Map.tileMap[c][a])};RR.Map.generateTileMap=function(){var a,c;RR.Map.tileMap=[];for(a=0;a<RR.Map.maxRows;a+=1)for(RR.Map.tileMap[a]={},c=0;c<RR.Map.maxCols;c+=1)RR.Map.tileMap[a][c]=RR.Map.sprite.data[RR.getRandomInt(0,RR.Map.dimTiles-1)]};
RR.Map.generateCollisionMap=function(){var a=0,c=0;RR.Map.borderCollisionMap=[];RR.Map.collisionMap=[];RR.Map.borderCollisionMap.push({fromX:0,fromY:0,toX:RR.Map.canvas.width,toY:RR.Map.borderWidth/2});RR.Map.borderCollisionMap.push({fromX:0,fromY:0,toX:RR.Map.borderWidth/2,toY:RR.Map.canvas.height});RR.Map.borderCollisionMap.push({fromX:0,fromY:RR.Map.canvas.height-RR.Map.borderWidth/2,toX:RR.Map.canvas.width-100,toY:RR.Map.canvas.height});RR.Map.borderCollisionMap.push({fromX:RR.Map.canvas.width-
RR.Map.borderWidth/2,fromY:0,toX:RR.Map.canvas.width,toY:RR.Map.canvas.height-100});RR.Map.borderCollisionMap.push({fromX:RR.Map.canvas.width-(RR.Map.borderWidth-2),fromY:RR.Map.canvas.height-40,toX:RR.Map.canvas.width,toY:RR.Map.canvas.height});for(a=0;a<RR.Map.maxRows;a+=1)for(RR.Map.collisionMap[a]={},c=1;c<RR.Map.maxCols-1;c+=1)RR.Map.collisionMap[a][c]=[],RR.Map.tileMap[a][c].hitboxes.forEach(function(b){RR.Map.collisionMap[a][c].push({fromX:b.fromX+100*c,fromY:b.fromY+100*a,toX:b.toX+100*c,
toY:b.toY+100*a})})};
RR.Map.checkCollision=function(a,c,b,d){var f=RR.Game.getNextGridTile(b,d,c);c={};var g=RR.Player.sprite.data[0].width/2-5,h=RR.Player.sprite.data[0].height/2-5;new RR.Vector2(0,0);var e=[];e.push.apply(e,RR.Map.borderCollisionMap);e.push.apply(e,RR.Map.collisionMap[b][d]);!1!==f&&e.push.apply(e,RR.Map.collisionMap[f.row][f.col]);c.fromX=a.x-g;c.toX=a.x+g;c.fromY=a.y-h;c.toY=a.y+h;a=e.length;for(b=0;b<a;b+=1)if(RR.rectanglesIntersect(e[b],c))return RR.isDevMode&&(RR.Map.ctx.strokeStyle="#FFFFFF",
RR.Map.ctx.lineWidth=1,RR.Map.ctx.fillStyle="transparent",RR.Map.ctx.strokeRect(e[b].fromX,e[b].fromY,e[b].toX-e[b].fromX,e[b].toY-e[b].fromY),RR.Map.ctx.strokeStyle="#AA0000",RR.Map.ctx.strokeRect(c.fromX,c.fromY,c.toX-c.fromX,c.toY-c.fromY)),RR.Player.drawSprite(),!0;return!1};RR.Map.generateNewMap=function(){RR.Map.generateTileMap();RR.Map.generateCollisionMap();RR.Map.drawMap();RR.Map.drawStart();RR.Map.drawOuterBorder();RR.Map.drawFinish()};
RR.Map.init=function(a,c,b,d,f){RR.Map.canvas=a;RR.Map.ctx=c;RR.Map.sprite=b;RR.Map.dimTiles=RR.Map.sprite.data.length;RR.Map.maxRows=d;RR.Map.maxCols=f;"string"===typeof RR.config.map.floorColor&&(RR.Map.floorColor=RR.config.map.floorColor)};RR.Player={canvas:{},ctx:{},sprite:{},state:{}};RR.Player.clearSprite=function(){RR.Player.ctx.clearRect(RR.Player.state.pos.x-RR.Player.sprite.halfWidth,RR.Player.state.pos.y-RR.Player.sprite.halfHeight,RR.Player.sprite.img.width,RR.Player.sprite.img.height)};
RR.Player.clearAll=function(){RR.Player.ctx.clearRect(0,0,RR.Player.canvas.width,RR.Player.canvas.height)};
RR.Player.drawSprite=function(){var a=RR.Player.state.angle*Math.PI/180,c=RR.Player.state.pos.x,b=RR.Player.state.pos.y;RR.Player.ctx.translate(c,b);RR.Player.ctx.rotate(a);RR.ctx.player.drawImage(RR.Sprites.stack.vehicle.img,0,0,RR.Player.sprite.data[0].width,RR.Player.sprite.data[0].height,-RR.Player.sprite.halfWidth,-RR.Player.sprite.halfHeight,RR.Player.sprite.img.width,RR.Player.sprite.img.height);RR.Player.ctx.rotate(-a);RR.Player.ctx.translate(-c,-b)};
RR.Player.changeAngle=function(a){RR.Player.state.angle=(RR.Player.state.angle+a+360)%360};RR.Player.rotateClockwise=function(){RR.Player.clearSprite();RR.Player.changeAngle(RR.Player.state.angularSpeed);RR.Player.drawSprite()};RR.Player.rotateAntiClockwise=function(){RR.Player.clearSprite();RR.Player.changeAngle(-RR.Player.state.angularSpeed);RR.Player.drawSprite()};RR.Player.startEngine=function(){RR.state.isRunning=!0;RR.Game.loop()};RR.Player.stopEngine=function(){RR.state.isRunning=!1};
RR.Player.reset=function(a){RR.Player.state={pos:new RR.Vector2(25,25),tile:{row:0,col:0},angle:90,angularSpeed:90,speed:1+.25*RR.state.level,lives:"number"===typeof a?a:5}};RR.Player.init=function(a,c,b){RR.Player.canvas=a;RR.Player.ctx=c;RR.Player.sprite=b;RR.Player.sprite.halfWidth=RR.Player.sprite.data[0].width/2;RR.Player.sprite.halfHeight=RR.Player.sprite.data[0].height/2;RR.Player.reset()};RR.Sprites={stack:{},stackTotal:0,stackIndex:0,callback:{}};
RR.Sprites.countUpStack=function(){RR.Sprites.stackIndex+=1;RR.Sprites.stackIndex>=RR.Sprites.stackTotal&&"function"===typeof RR.Sprites.callback&&RR.Sprites.callback()};
RR.Sprites.load=function(a,c){if("object"!==typeof a)return console.log("[Error] Missing Or Invalid Argument"),!1;var b=Object.keys(a),d;RR.Sprites.stackTotal=b.length;"function"===typeof c&&(RR.Sprites.callback=c);for(d=0;d<RR.Sprites.stackTotal;d+=1)RR.Sprites.stack[b[d]]={},RR.Sprites.stack[b[d]].data=a[b[d]].data[b[d]],RR.Sprites.stack[b[d]].img=new Image,RR.Sprites.stack[b[d]].img.addEventListener("load",RR.Sprites.countUpStack),RR.Sprites.stack[b[d]].img.src=a[b[d]].image};
RR.Vector2=function(a,c){var b=this;this.directionY=this.directionX=this.magnitude=this.y=this.x=0;this.get=function(){return{x:b,y:b}};this.set=function(a,c){b.x=a;b.y=c;b.calculateMagniture();b.calculateDirection()};this.times=function(a){b.x*=a;b.y*=a};this.dividedBy=function(a){b.x/=a;b.y/=a};this.add=function(a){b.x+=a;b.y+=a};this.substract=function(a){b.x-=a;b.y-=a};this.calculateMagniture=function(){b.magnitude=Math.sqrt(b.x*b.x+b.y*b.y)};this.getMagnitude=function(){return b.magnitude};this.calculateDirection=
function(){b.directionX=b.x/b.magnitude;b.directionY=b.y/b.magnitude};this.getDirection=function(a){"boolean"===typeof a&&a&&this.calculateDirection();return{x:b.directionX,y:b.directionY}};b.set(a,c)};